spring:
  datasource:
    url: jdbc:mysql://178.128.21.202:3306/toy_r?useSSL=false
    username: root
    password: sckshuhari
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
